import { Inter, Nunito, Nunito_Sans } from 'next/font/google'
import './globals.css'

const nunito = Nunito({
  subsets: ['latin'],
  weight: ["400", "700", "900"],
  variable: '--font-nunito'
})
const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  weight: ["400", "700", "900"],
  variable: '--font-nunito-sans'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
